# Generated by Django 4.0.5 on 2022-06-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='label',
            new_name='lavel',
        ),
    ]
